### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by BirkhoffLee** [CaptnSisko/forumsync#1]
Hey there, could you add more description to the repo? Thank you so much.

**Comment by CaptnSisko** [comment]
If there is more interest in this plugin, I might add more documentation over the summer. At the moment, many values (such as groups)  are hard coded into the Java, so it would take some editing to make this plugin to work with any server. Out of curiosity, what are you planning on using it for?

**Comment by BirkhoffLee** [comment]
Obviously, I'll be using it on my Minecraft server and phpBB.

And I just read through the code, I think I can change it to my needs by myself, since you're using MIT license. So imma just fork it. Thanks!
