### ISSUE TITLE
Group numbers

### ISSUE THREAD

**Issue by BirkhoffLee** [CaptnSisko/forumsync#2]
Hey again! :) May I know what does the group numbers stand for?

https://github.com/CaptnSisko/forumsync/blob/master/src/me/sisko/phpbb/RankSync.java#L51

Thanks!

**Comment by CaptnSisko** [comment]
You need to create ranks in phpbb which correspond to ranks in game. There is an SQL table which contains the rank IDs.

**Comment by BirkhoffLee** [comment]
Alright, thanks!
